### ISSUE TITLE
Unable to resolve dependencies.

### ISSUE THREAD

**Issue by piedatt80** [leonardoporro/EntityFrameworkCore.Detached#1]
First of all congratulations for your initiative! I went into crisis when I realized that GraphDiff does not work with version EntityFrameworkCore. I hope that your project goes ahead. It would be very interesting!

But here's the problem: 
"Unable to resolve dependencies. 'Microsoft.EntityFrameworkCore 1.0.1' is not compatible with 'EntityFrameworkCore.Detached 1.0.0-alpha8 constraint: Microsoft.EntityFrameworkCore (>= 1.1.0-alpha1-22131)".

**Comment by leonardoporro** [comment]
Hi Pietro! Thanks a lot for writting. 
Please remember that you need to add a nuget source (myget) to get EF Core alpha packages:

"In order to get alpha EF Core dependencies, you would need to add myget.org to the nuget sources. Go to menu "Tools -> Options -> NuGet Package Manager -> Package Sources" and add this source: https://dotnet.myget.org/F/aspnetcore-dev/ 
Then you will be able to download EF Core 1.1.0-alpha..."

And please use version alpha1-14: https://www.nuget.org/packages/EntityFrameworkCore.Detached/1.0.0-alpha1-14

It seems that alpha8 is bigger than alpha14 (evaluated as strings) so I had to change the version.
Sorry, my bad.

Please let me know how it goes and if I can help you with anything.

**Comment by piedatt80** [comment]
I followed all the steps, and now it all works correctly.
In this period I am considering whether to upgrade my application in WPF/MVVM/EntityFramework 6.1.3 in EntityFrameworkCore 1.0.1, but a bad discovery was the non-operation of GraphDiff with EntityFrameworkCore 1.0.1
Therefore, I will follow with great interest the development of your project. You advance already being interested in examples make use of Generic Repository.
I close.

**Comment by leonardoporro** [comment]
Thanks for following!
I will update the package to a beta/release version as soon as EF Core 1.1.0 is released so myget.org won't be needed anymore and it will work out of the box (sorry for the inconveniences, it is an alpha).
Let me know if you need any other help.
